import {
  adults,
  air_conditioner,
  automatic,
  beds,
  cd,
  freezer,
  gas,
  hob,
  kitchen,
  microwave,
  petrol,
  radio,
  shower,
  toilet,
  tv,
  water,
} from '../../assets/icons';

export const fullObjectProperties = {
  adults: { name: 'Adults', icon: adults },
  CD: { name: 'CD', icon: cd },
  automatic: { name: 'Automatic', icon: automatic },
  airConditioner: { name: 'Air conditioner', icon: air_conditioner },
  bathroom: { name: 'Bathroom', icon: automatic },
  beds: { name: 'Transmission', icon: beds },
  kitchen: { name: 'Kitchen', icon: kitchen },
  engine: { name: 'Petrol', icon: petrol },
  freezer: { name: 'Freezer', icon: freezer },
  gas: { name: 'Gas', icon: gas },
  hob: { name: 'Hob', icon: hob },
  microwave: { name: 'Microwave', icon: microwave },
  shower: { name: 'Shower', icon: shower },
  toilet: { name: 'Toiler', icon: toilet },
  water: { name: 'Water', icon: water },
  radio: { name: 'Radio', icon: radio },
  TV: { name: 'TV', icon: tv },
};
